.data
 TN     DWORD 8  ;;; # of tests
 CASE   DWORD 6				    ;;; list size (CASE: start of input)
 HEIGHT	DWORD 6, 4, 1, 1, 3, 4  ;;; heights measured (1st test)
        DWORD 8                          ;;; list size(2nd test)
        DWORD 3, 4, 4, 11, 1, 20, 12, 1  ;;; height measured(2nd test)				; ans 19
        DWORD 10
        DWORD 8, 9, 33, 43, 14, 19, 23, 23, 24, 50
        DWORD 9
        DWORD 10,  7,  3,  10,  12,  10,  6,  6 , 1
        DWORD 10
        DWORD 1, 2,3,4,5,6,7,8,9,10
        DWORD 10
        DWORD 9,8,7,6,5,4,3,2,1,0
        DWORD 2
        DWORD 9,0
        DWORD 2
        DWORD 1,3
            
    

 